#!/bin/bash

# Set the desired dock settings
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock last-messagetrace-stamp -string "722241627.424284"
defaults write com.apple.dock launchanim -bool false
defaults write com.apple.dock loc -string "en_US:US"
defaults write com.apple.dock magnification -bool false
defaults write com.apple.dock mineffect -string "scale"
defaults write com.apple.dock mod-count -int 9
defaults write com.apple.dock orientation -string "right"
defaults write com.apple.dock persistent-apps -array
defaults write com.apple.dock persistent-others -array
defaults write com.apple.dock recent-apps -array
defaults write com.apple.dock region -string "US"
defaults write com.apple.dock show-process-indicators -bool false
defaults write com.apple.dock show-recents -bool false
defaults write com.apple.dock tilesize -int 128
defaults write com.apple.dock trash-full -bool true
defaults write com.apple.dock version -int 1
osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to true'
# Restart the Dock for changes to take effect
killall Dock
osascript -e 'tell application "System Events" to tell every desktop to set picture to ""'
